---
- name: deploy image on development vm 
  hosts: "{{ host_ip }}"
  become: yes
  
  vars:
    default_container_name: mysql_apllication
    default_image_name: "{{ image_name }}"
    image_version: "{{ image_tag }}"
  
  tasks:

    - name: Install pip
      package:
        name: python-pip
        state: present
        update_cache: yes
    
    - name: Install setuptools
      pip:
        name: setuptools
        state: present

    - name: Install Docker SDK
      pip:
        name: docker
        state: present
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull development environment docker image
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_image_name }}:{{ image_version }}"
        env_file: "{{ env_credentials_path }}"
        state: started
        expose:
          - 8080
        ports:
          - "8080:8080"
    
    - name: Get info
      docker_container_info:
        name: "{{ default_container_name }}"
      register: result
    
    - name: Print information about container
      debug:
        var: result.container
      when: result.exists
