---
- hosts: docker_hosts
  become: true
  vars:
    default_image_name: nikspanos/cicd-pipeline_dev
    image_version: version5
  gather_facts: no
  tasks:
    - name: Pull development environment docker image
      docker_image:
        name: "{{ default_image_name }}"
        tag: "{{ image_version }}"
        state: present
        source: pull