---
- hosts: docker_hosts
  gather_facts: no
  tasks:
    - name: copy tarball to host
      copy:
        src: "./application_dev_{{ image_version }}.tar"
        dest: "/root/application_dev_{{ image_version }}.tar"
    - name: load container from tarball
      docker_image:
        name: nikspanos/cicd-pipeline_dev
        tag: "{{ image_version }}"
        load_path: "/root/application_dev_{{ image_version }}.tar"
        state: present
        source: load